# 项目相关配置
sen:
  # 名称
  name: sen_user
  # 版本
  version: 1.0.0
  # 验证码类型 match 数组计算 char 字符验证
  captchaType: math

server:
  port: 8080

logging:
  level:
    com.sen: debug
    org.springframework: warn


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sen?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 123456

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:

    # 连接超时时间
    timeout: 50s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥，这个地方改了的话，密码会失效，
  secret: P5J9Ua4QAeKYgYqVeDihKyUpu1
  # 令牌有效期（默认30分钟）
  expireTime: 30

# mybatis-plus 配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.sen.**.domain, com.sen.common.core.domain.entity,  com.sen.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: auto
      update-strategy: ignored
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /
