# 项目相关配置
sen:
  # 名称
  name: sen_user
  # 版本
  version: 1.0.0

server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sen?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 123456
